# Generated by Django 3.1.7 on 2021-04-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pivots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
