# Generated by Django 3.1.7 on 2021-04-14 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pivots', '0002_customer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='documents',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='customer',
            name='data_sheet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pivots.datasheet'),
        ),
    ]
